[build]
  publish = "WEBSITE/dist"

# Handle all assets directly from Framer
[[redirects]]
  from = "https://edoardograci.com/*"
  to = "https://charismatic-everyone-653587.framer.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify", X-Robots-Tag = "index, follow"}

# Remove Framer analytics script
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-src 'self'"

# Fallback redirect
[[redirects]]
  from = "/*"
  to = "https://charismatic-everyone-653587.framer.app/:splat"
  status = 200
  force = true
